#!/bin/bash

source "${OPENSHIFT_RUBY_DIR}/lib/ruby_context"
pushd ${OPENSHIFT_REPO_DIR} 1> /dev/null
SAVED_GIT_DIR=$GIT_DIR
unset GIT_DIR
sed -i s/-x86-mingw32// Gemfile.lock
sed -i s/x86-mingw32/ruby/ Gemfile.lock
#ruby_context "gem install bundler:1.10.6"
export GIT_DIR=$SAVED_GIT_DIR
popd 1> /dev/null